name = "RationalSimplex"                                                                                  
uuid = "1181f4b9-0ba3-4b3e-a982-d971b817e3a1"                                                                      
version = "0.1.0"     
